
// Populate the databse:

###
//C: create (Cars)
POST http://localhost:3000/cars/populate
Content-Type: application/json
###
//C: create (Bikes)
POST http://localhost:3000/bikes/populate
Content-Type: application/json
###
//C: create (Planes)
POST http://localhost:3000/planes/populate
Content-Type: application/json
###
//C: create (CUSTOM) - (follow validator rules found in carSchema (/models/car.mjs))
POST http://localhost:3000/cars

//  Template:
{
    "make": "",
    "model": "",
    "year": ,
    "inProduction": false,
}

// Read database:

###
//R: read All cars
GET http://localhost:3000/cars
###
//R: read All bikes
GET http://localhost:3000/bikes
###
//R: read All planes
GET http://localhost:3000/planes
###
//R: read (CUSTOM) by object_id
GET http://localhost:3000/"collectionName/object_id"


// Update database:

###
//U: update by Object_id (eg: '/cars/_id')
PATCH http://localhost:3000/cars/"object_id"
Content-Type: application/json

// data to modify:
{
    "inProduction": true
}


// clean up:
###
//D: delete ALL
DELETE http://localhost:3000/cars/

###
//D: delete ALL
DELETE http://localhost:3000/bikes/

###
//D: delete ALL
DELETE http://localhost:3000/planes/

###
//D: delete (CUSTOM) by object_id
DELETE http://localhost:3000/"collectionName/object_id"
