//C: create one (CUSTOM CAR)
POST http://localhost:3000/cars
Content-Type: application/json
// FILL OUT ALL REQUIRED FIELDS:
{
    "make": "",
    "model": "",
    "year": ,
    "inProduction":
}

###
//C: create one (all fields are required) - FOR TESTING
POST http://localhost:3000/cars
Content-Type: application/json

{"make": "BMW"}

###
//R: read All or one (by ObjectID). eg: '/cars/_id'
GET http://localhost:3000/planes

###
//U: update one (by ObjectID). eg: '/cars/_id'
PATCH http://localhost:3000/cars/("_id" GOES HERE)
Content-Type: application/json

// data to modify:
{
    "inProduction": true
}

###
//D: delete ALL or one (specified by '/cars/_id')
DELETE http://localhost:3000/cars/
